### PR TITLE
Curriculum assignment

### PR DESCRIPTION
**Pull request by NatePadgett**

### CODE REVIEW

**Comment by NatePadgett** [comment]
Merging my fork with Taeyoon's master.

**Comment by tchoi8** [comment]
This is a well thought out response to the assignment. 
I'd suggest looking into examples of [Portfolio School](https://www.portfolio-school.com/) or [Instittue of Play](https://www.instituteofplay.org/).

I'd investigate the pros and cons of project-based learning and multidisciplinary approach.

**Comment by TaeyoonTA** [comment]
Hi Nate! This is really awesome work, you've drawn out excellent learning outcomes and objectives through your detailed scheduling and readings. I really like the standard yet flexible reflections you've built into this course. I think this would be a super interesting and beneficial course for students of all ages.

**Comment by NatePadgett** [comment]
Thank you Taeyoon! This is exactly the type of class I would have loved in
high school but never had an opportunity to take (because nothing like it
was taught). I look forward to discussing it more in class! I also want to
talk with you about the use of GitHub.
ᐧ

**Pull request merged**
